added custom log server config to rsyslog role
osism/ansible-collection-services pull request #645
Opened 2022-03-28 12:43 UTC by muellerbe

Signed-off-by: Bernd Mueller <mueller@b1-systems.de>

2022-03-28 13:03 UTC, berendt requested changes

2022-03-29 06:35 UTC, muellerbe commented on roles/rsyslog/tasks/custom-log-server.yml
> +- name: Forward syslog message to custom log server
you are right, changed

2022-03-29 06:35 UTC, muellerbe commented on roles/rsyslog/tasks/main.yml
> +  when: rsyslog_custom_host is defined
changed

2022-03-29 09:51 UTC, berendt approved these changes

2022-03-29 16:48 UTC, merged