Journald: Add documentation for the role
osism/ansible-collection-services pull request #736
Opened 2022-06-01 07:38 UTC by ra-rau

Part of osism/issues#185

Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

2022-06-01 07:46 UTC, berendt requested changes

2022-06-01 07:46 UTC, berendt commented on roles/journald/README.rst
> +This role configures options for Journald.
Use ``journald``everywhere.

2022-06-08 12:20 UTC, ra-rau commented on roles/journald/README.rst
> +This role configures options for Journald.
done

2022-07-13 07:22 UTC, berendt approved these changes

2022-07-13 07:23 UTC, merged